import { useEffect, useState } from "react";
import { ArrowLeft, ArrowUpLeft, Brain, Check, Cloud, Globe2, Menu, MessageCircle, ShieldCheck, Sparkles, Smartphone, Workflow, X, Zap } from "lucide-react";
import { content, type Language, type Service } from "../../shared/content";
import "./styles.css";

const icons = { globe: Globe2, sparkles: Sparkles, brain: Brain, workflow: Workflow, smartphone: Smartphone, cloud: Cloud } as const;
const copy = { ar: { home: "الرئيسية", services: "الخدمات", work: "أعمالنا", about: "من نحن", contact: "تواصل معنا", login: "دخول", start: "ابدأ مشروعك", hero: "من الفكرة إلى الأثر", body: "نصمم ونبني منتجات رقمية، منصات، أنظمة ذكاء اصطناعي وأتمتة تحول الطموح إلى نتائج قابلة للنمو.", discover: "اكتشف خدماتنا", workTitle: "نبني ما يحتاجه المستقبل", workBody: "استراتيجية واضحة، تصميم دقيق، وهندسة تجعل كل فكرة قابلة للتوسع.", process: "كيف نصنع الأثر؟", contactTitle: "جاهز تحول فكرتك إلى أثر؟", send: "أرسل طلبك" }, en: { home: "Home", services: "Services", work: "Work", about: "About", contact: "Contact", login: "Login", start: "Start a project", hero: "From idea to impact", body: "We design and build digital products, platforms, AI systems, and automation that turn ambition into measurable growth.", discover: "Explore services", workTitle: "We build what the future needs", workBody: "Clear strategy, precise design, and engineering that makes every idea scalable.", process: "How we create impact", contactTitle: "Ready to turn your idea into impact?", send: "Send request" } };

function Logo() { return <a className="logo" href="#top"><span className="mark">أ</span><span><b>ATHR</b><small>DIGITAL SOLUTIONS</small></span></a>; }
function App() {
  const [lang, setLang] = useState<Language>(() => (localStorage.getItem("athr-lang") as Language) || "ar");
  const [menu, setMenu] = useState(false); const [scrolled, setScrolled] = useState(false); const [formOpen, setFormOpen] = useState(false); const [sent, setSent] = useState(false);
  const t = copy[lang]; const rtl = lang === "ar";
  useEffect(() => { document.documentElement.lang = lang; document.documentElement.dir = rtl ? "rtl" : "ltr"; localStorage.setItem("athr-lang", lang); const onScroll = () => setScrolled(scrollY > 24); addEventListener("scroll", onScroll); return () => removeEventListener("scroll", onScroll); }, [lang, rtl]);
  const toggle = () => setLang(lang === "ar" ? "en" : "ar");
  return <div id="top" className="app">
    <header className={scrolled ? "header scrolled" : "header"}><Logo/><nav className={menu ? "nav open" : "nav"}>{[["#top", t.home],["#services", t.services],["#work", t.work],["#about", t.about],["#contact", t.contact]].map(([href, label]) => <a key={href} href={href} onClick={() => setMenu(false)}>{label}</a>)}</nav><div className="header-actions"><button className="text-button" onClick={toggle}>{rtl ? "English" : "العربية"}</button><button className="outline-button">{t.login}</button><button className="gold-button small" onClick={() => setFormOpen(true)}>{t.start}<ArrowUpLeft size={15}/></button></div><button className="menu-button" onClick={() => setMenu(!menu)} aria-label="menu">{menu ? <X/> : <Menu/>}</button></header>
    <main>
      <section className="hero"><div className="hero-copy"><span className="eyebrow"><Zap size={15}/> ATHR DIGITAL SOLUTIONS</span><h1>{t.hero}</h1><p>{t.body}</p><div className="hero-actions"><button className="gold-button" onClick={() => setFormOpen(true)}>{t.start}<ArrowUpLeft size={18}/></button><a className="outline-button" href="#services">{t.discover}<ArrowLeft size={17}/></a></div><div className="trust"><ShieldCheck size={17}/> {rtl ? "بنية رقمية آمنة وقابلة للتوسع" : "Secure, scalable digital foundations"}</div></div><HeroVisual/></section>
      <section className="stats">{content.stats.map(s => <div className="stat" key={s.value}><strong>{s.value}<em>+</em></strong><span>{rtl ? s.labelAr : s.labelEn}</span></div>)}</section>
      <section id="services" className="section"><div className="section-heading"><span className="eyebrow">01 / {rtl ? "ما نبنيه" : "WHAT WE BUILD"}</span><h2>{t.workTitle}</h2><p>{t.workBody}</p></div><div className="service-grid">{content.services.map(service => <ServiceCard key={service.id} service={service} rtl={rtl}/>)}</div></section>
      <section id="work" className="section dark-section"><div className="section-heading"><span className="eyebrow">02 / {rtl ? "مختارات من أعمالنا" : "SELECTED WORK"}</span><h2>{rtl ? "أثر ملموس، لا وعود فقط" : "Visible impact, not just promises"}</h2></div><div className="project-grid">{content.projects.map(project => <article className="project" key={project.id}><img src={project.image} alt="" loading="lazy"/><div className="project-overlay"><span>{project.category}</span><h3>{project.title}</h3><p>{project.description}</p></div></article>)}</div></section>
      <section id="about" className="split-section"><div><span className="eyebrow">03 / {rtl ? "منهجنا" : "OUR METHOD"}</span><h2>{t.process}</h2></div><div className="process-list">{["الاكتشاف / Discovery", "الاستراتيجية / Strategy", "التصميم / Design", "التطوير / Development", "الإطلاق / Launch"].map((p, i) => <div className="process-item" key={p}><b>0{i + 1}</b><span>{rtl ? p.split(" / ")[0] : p.split(" / ")[1]}</span><Check size={17}/></div>)}</div></section>
      <section id="contact" className="cta"><div><span className="eyebrow">04 / {rtl ? "الخطوة التالية" : "NEXT STEP"}</span><h2>{t.contactTitle}</h2></div><button className="gold-button" onClick={() => setFormOpen(true)}>{t.send}<ArrowUpLeft size={18}/></button></section>
    </main><footer><Logo/><span>© {new Date().getFullYear()} ATHR Digital Solutions</span></footer>{formOpen && <ContactModal rtl={rtl} sent={sent} setSent={setSent} close={() => { setFormOpen(false); setSent(false); }}/>}<button className="chat" aria-label="support"><MessageCircle size={21}/></button>
  </div>;
}
function HeroVisual() { return <div className="visual"><div className="orbit one"/><div className="orbit two"/><div className="cube"><span>أ</span></div><i className="particle p1"/><i className="particle p2"/><i className="particle p3"/></div>; }
function ServiceCard({ service, rtl }: { service: Service; rtl: boolean }) { const Icon = icons[service.icon as keyof typeof icons] || Sparkles; const data = rtl ? service.ar : service.en; return <article className="service-card"><div className="icon"><Icon size={23}/></div><h3>{data.name}</h3><p>{data.description}</p><a href={`/services/${service.slug}`}>{rtl ? "اكتشف الخدمة" : "Explore service"}<ArrowLeft size={15}/></a></article>; }
function ContactModal({ rtl, sent, setSent, close }: { rtl: boolean; sent: boolean; setSent: (v: boolean) => void; close: () => void }) { const [form, setForm] = useState({ name: "", email: "", message: "" }); const [loading, setLoading] = useState(false); const submit = async (e: React.FormEvent) => { e.preventDefault(); setLoading(true); try { const res = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (res.ok) setSent(true); } finally { setLoading(false); } }; return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && close()}><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={close}><X/></button>{sent ? <div className="success"><Check size={42}/><h3>{rtl ? "تم استلام طلبك" : "Request received"}</h3><p>{rtl ? "سنتواصل معك قريباً." : "We will be in touch soon."}</p></div> : <><span className="eyebrow">{rtl ? "ابدأ مشروعك" : "START A PROJECT"}</span><h2>{rtl ? "احكِ لنا عن فكرتك" : "Tell us about your idea"}</h2><label>{rtl ? "الاسم" : "Name"}<input required minLength={2} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></label><label>{rtl ? "البريد الإلكتروني" : "Email"}<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/></label><label>{rtl ? "رسالتك" : "Message"}<textarea required minLength={10} value={form.message} onChange={e => setForm({ ...form, message: e.target.value })}/></label><button className="gold-button" disabled={loading}>{loading ? "..." : rtl ? "إرسال الطلب" : "Send request"}<ArrowUpLeft size={17}/></button></>}</form></div>; }
export default App;
